# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grounds < Formula
  desc "Grounds Internal Developer Platform CLI"
  homepage "https://grounds.gg"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.1/grounds-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "62101edac1fcc4eb50886dad9b823d5d42270cd9de08823edcddc4dadda551f5"

      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.1/grounds-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "f9151efc6e04451419f177fc7d0d2e2f5c1391d29b9e40bd32bab5dd932dd7ba"

      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.1/grounds-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "3de423d340554bf8aa4500c109ed7164c0d8c4518b6eed06c1998e69d91b907a"
      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.1/grounds-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "b0e4559ae71f85d8e8940167097d1eb37ae16d87075a05b02c418867169a7651"
      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
  end

  test do
    assert_match "grounds version", shell_output("#{bin}/grounds version")
  end
end
