# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grounds < Formula
  desc "Grounds Internal Developer Platform CLI"
  homepage "https://grounds.gg"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.4/grounds-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "e2fce66ad7d7b114346102570023b3940a27d9200e0feec35dc3d60511b6fbdd"

      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.4/grounds-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "d12d616434f690a569235f752eb3c43c59f5fbc04d817a8fd415757cdf5be742"

      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.4/grounds-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "5b50f1e317895aedbeb5ef381dd2191430a43cd45559400e1f37782dae89d767"
      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.4/grounds-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "e5c09b48b4c15ed2870402e15cb4d1651f6f7c18a1e19084c24d4d908654e7b5"
      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
  end

  test do
    assert_match "grounds version", shell_output("#{bin}/grounds version")
  end
end
