# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grounds < Formula
  desc "Grounds Internal Developer Platform CLI"
  homepage "https://grounds.gg"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.2/grounds-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "e280464b4bd772beaa8aadde8c99434ba16274306796c8412fd47fd45c8a5881"

      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.2/grounds-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "6a3d9096ad184c877a77bf6412fe9ed41d84c88bf9e20f678253dcb7cdd19ded"

      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.2/grounds-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "d6914ed4c0735ff7a701b2cc788f3c5a53988a3f3bef807d343208cd51118afb"
      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/groundsgg/grounds-cli/releases/download/v0.1.2/grounds-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "e56b4cf926e665e7ce502a836ca39898414b97925ba011961dd130e3fa4f6b63"
      define_method(:install) do
        bin.install "grounds"
        generate_completions_from_executable(bin/"grounds", "completion")
      end
    end
  end

  test do
    assert_match "grounds version", shell_output("#{bin}/grounds version")
  end
end
