# This file was generated by GoReleaser. DO NOT EDIT.
cask "grounds" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "49c1479c1cc9e6d33b09adc265f8434eea71867adb18fc20946a87f6157dcaad"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
    on_arm do
      sha256 "de8a4a0fe563751a047f4700bd99b72b138823da8cdab029c139629f3270b819"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "76eaea00370b7529ab95c604561538ce9a1ca1bf04ad58d4c062dbc88e308043"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
    on_arm do
      sha256 "14cac7a77c30bb02fbd5dec0e71a1a84712e3897f8173a498736167c06afdaeb"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
  end

  name "grounds"
  desc "Grounds Developer Platform CLI"
  homepage "https://grounds.gg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grounds"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grounds"]
    end
  end

  # No zap stanza required

end
