# This file was generated by GoReleaser. DO NOT EDIT.
cask "grounds" do
  version "0.1.10"

  on_macos do
    on_intel do
      sha256 "ce6a2f269f620c73b38071e52c77fa6df46f03863cf485e5a440555ef8f05eaa"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebdb59ca9459c83517349667254c344652a531a52688bfab59ff60064e4bc513"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc255693bc7330e6e441068a0217f0526405e45d5b12378d8805760d1066016d"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "781482d60d7ed3aeac358eed36b01ce785a0c7690c538cdb32a36292dfaa7fc3"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "grounds"
  desc "Grounds Internal Developer Platform CLI"
  homepage "https://grounds.gg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grounds"
  generate_completions_from_executable "bin/grounds", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
