# This file was generated by GoReleaser. DO NOT EDIT.
cask "grounds" do
  version "0.1.19"

  on_macos do
    on_intel do
      sha256 "262dcbfce15cc47e6e2c90cfbaefc7afe4fac3d383f02e5021e179e4244ffe33"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
    on_arm do
      sha256 "a8bf410a4c1dbeb7eb77366a6ca58987850009f62abd8c9bcda6ae6e4ba5250e"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "60623606838d9a12bd0f601116584d329ae008782b80df41553a7b343933070c"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
    on_arm do
      sha256 "ca9b69386c900368109dd0579869c863de2ec86ff1ac55fe7756041358f10307"
      url "https://github.com/groundsgg/grounds-cli/releases/download/v#{version}/grounds-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/groundsgg/grounds-cli"
    end
  end

  name "grounds"
  desc "Grounds Developer Platform CLI"
  homepage "https://grounds.gg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grounds"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grounds"]
    end
  end

  # No zap stanza required

end
